CREATE TABLESPACE TABLESPACE2
DATAFILE 'D:\oracle\Academey\TEST_TBS1.DBF' SIZE 10M
AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED -- 추가되는 용량
LOGGING -- 로깅사용
EXTENT MANAGEMENT LOCAL AUTOALLOCATE -- LOCAL
BLOCKSIZE 8k -- 블록크기 8k
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON; -- 테이블 추가 및 설정

-- table space rename 이름바꾸기
ALTER TABLESPACE TABLESPACE2
RENAME TO TEST_TBS_NEW;

-- 파일 용량수정
ALTER DATABASE
DATAFILE 'D:\oracle\Academey\TEST_TBS1.DBF' RESIZE 20M;

-- TABLESPACE DELETE
DROP TABLESPACE TABLESPACE1
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS; -- 무결성


-- TABLE 생성 하기
CREATE TABLE TB_TEST01(COL_01 VARCHAR2(10), COL_02 VARCHAR2(10), COL_03 VARCHAR2(10), COL_04 VARCHAR2(10));
-- 생성시 디폴트 값이 users로 생성이된다.

CREATE TABLE TB_TEST02 (COL_01 VARCHAR2(10), COL_02 VARCHAR2(10), COL_03 VARCHAR2(10), COL_04 VARCHAR2(10), COL_05 VARCHAR2(10))
TABLESPACE TABLESPACE2; -- TABLESPACE2 참조

-- TABLE COPY : 데이터 포함
CREATE TABLE TB_TEST03 AS SELECT * FROM jobs;

SELECT * FROM tb_test03; -- 확인

DROP TABLE tb_test03;

CREATE TABLE TB_TEST03 AS SELECT job_id, job_title FROM jobs; -- 원하는 컬럼만 추려서 테이블을 만들 수 있음.

SELECT * FROM tb_test03; -- 재확인

CREATE TABLE TB_TEST03 AS SELECT job_id AS 업무번호, job_title"업무명" FROM jobs;

CREATE TABLE TB_GROUP_DEPT
AS -- CREATE에서 복사의 역할을 한다.
SELECT department_id"부서번호", SUM(salary)"합계", AVG(salary)"평균" FROM employees -- COLUMN명을 변경해서 복사한다.
GROUP BY department_id;

SELECT *FROM tb_group_dept;

DROP TABLE tb_group_dept;

-- TABLE COPY : 데이터 미포함
CREATE TABLE TB_TEST04
AS
SELECT *
FROM departments
WHERE 1=2; -- 성립하지 않는 조건을 기입할시 데이터가 포함되지 않고 테이블만 가져온다(COLUMN).

SELECT * FROM tb_test04;

-- TABLE : CREATE, ALTER, DROP
-- DATA : INSERT, UPDATE, DELETE, SELECT

-- TABLE 수정 : 테이블명 수정
ALTER TABLE TB_TEST04
RENAME TO TB_TEST99;

-- TABLE 수정 : 단일 컬럼 추가.
ALTER TABLE TB_TEST99
ADD
LOCATION_NAME VARCHAR2(30);

SELECT *
FROM TB_TEST99;

-- TABLE 수정 : 다중컬럼 추가
ALTER TABLE TB_TEST99
ADD
(COL_01 VARCHAR2(30), COL_02 NUMBER(5,2));

-- TABLE 수정 : 단일컬럼 수정

ALTER TABLE TB_TEST99
MODIFY
(COL_01 VARCHAR2(20));

-- TABLE 수정 : 다중컬럼 수정
ALTER TABLE TB_TEST99
MODIFY
(COL_01 VARCHAR2(40), COL_02 NUMBER(6,2));

-- TABLE 수정 : 컬럼 삭제
ALTER TABLE TB_TEST99
DROP COLUMN LOCATION_NAME;

-- TABLE 수정 : 컬럼 삭제
ALTER TABLE TB_TEST99
DROP (COL_01, COL_02);

-- TABLE 수정 : 컬럼명 수정
ALTER TABLE TB_TEST99
RENAME COLUMN DEPARTMENT_ID TO "부서번호";

-- TABLE
DROP TABLE TB_TEST01;

DROP TABLE TB_TEST02
CASCADE CONSTRAINTS; -- 제약조건까지 사라짐. 무결성

-- 휴지통에서 복구
FLASHBACK TABLE TB_TEST02
TO BEFORE DROP;

-- 휴지통 비우기
PURGE RECYCLEBIN;